# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab02', '0002_auto_20160521_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab02.Photographer'),
        ),
    ]
