# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab02', '0003_auto_20160521_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cameras',
            field=models.ManyToManyField(blank=True, to='lab02.Camera'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='locations',
            field=models.ManyToManyField(blank=True, to='lab02.Location'),
        ),
    ]
