# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab02', '0004_auto_20160521_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together=set([('name', 'version')]),
        ),
    ]
