# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab02', '0005_auto_20160521_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
