# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab02', '0006_auto_20160521_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='year_created',
            new_name='date_created',
        ),
    ]
