-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 22:00:42 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lab02db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab02db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab02db` DEFAULT CHARACTER SET utf8 ;
USE `lab02db` ;

-- -----------------------------------------------------
-- Table `lab02db`.`Photographer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`Photographer` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`Photographer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `level` INT ZEROFILL NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab02db`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`Location` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`Location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  `accessible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab02db`.`Camera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`Camera` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`Camera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `year_created` DATETIME NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab02db`.`Photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`Photo` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`Photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `camera_id` INT NULL,
  `location_id` INT NULL,
  `photographer_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `aperture` FLOAT NULL,
  `iso` INT NULL,
  `shot_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Photo_Camera_idx` (`camera_id` ASC),
  INDEX `fk_Photo_Location_idx` (`location_id` ASC),
  INDEX `fk_Photo_Photographer_idx` (`photographer_id` ASC),
  CONSTRAINT `fk_Photo_Camera`
    FOREIGN KEY (`camera_id`)
    REFERENCES `lab02db`.`Camera` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Photo_Location`
    FOREIGN KEY (`location_id`)
    REFERENCES `lab02db`.`Location` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Photo_Photographer`
    FOREIGN KEY (`photographer_id`)
    REFERENCES `lab02db`.`Photographer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab02db`.`PhotographerCamera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`PhotographerCamera` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`PhotographerCamera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `camera_id` INT NOT NULL,
  `photographer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `camera_id_UNIQUE` (`camera_id` ASC),
  UNIQUE INDEX `photographer_id_UNIQUE` (`photographer_id` ASC),
  CONSTRAINT `fk_PhotographerCamera_Camera`
    FOREIGN KEY (`camera_id`)
    REFERENCES `lab02db`.`Camera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PhotographerCamera_Photographer`
    FOREIGN KEY (`photographer_id`)
    REFERENCES `lab02db`.`Photographer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab02db`.`PhotographerLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab02db`.`PhotographerLocation` ;

CREATE TABLE IF NOT EXISTS `lab02db`.`PhotographerLocation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photographer_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `photographer_id_UNIQUE` (`photographer_id` ASC),
  UNIQUE INDEX `location_id_UNIQUE` (`location_id` ASC),
  CONSTRAINT `fk_PhotographerLocation_Photographer`
    FOREIGN KEY (`photographer_id`)
    REFERENCES `lab02db`.`Photographer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PhotographerLocation_Location`
    FOREIGN KEY (`location_id`)
    REFERENCES `lab02db`.`Location` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
